language: node_js
sudo: required
dist: trusty
node_js:
- 12
before_install:
- bash bin/ci-setup
script: "bash bin/test"
after_script: heroku keys:remove $USER@`hostname`
matrix:
  fast_finish: true
  include:
    - jdk: openjdk7
    - jdk: oraclejdk8
    - jdk: oraclejdk11
